### ISSUE TITLE
NPM instructions from README.md

### ISSUE THREAD

**Issue by jcreamer898** [Code52/metro.css#23]
Are these instructions from the readme correct? 

```
npm install
node metro <path>
cd <path>
npm install
node app.js
```

Sure seems like there should be something after the install for both of those **npm install** commands...

```
npm install **metro**?
```

**Comment by csainty** [comment]
These are correct. npm install with no package name reads the package.config and installs all the dependencies in one hit.

The first call installs the dependencies needed by the script. The second one does the dependencies for the generated site.

**Comment by jcreamer898** [comment]
Well that's just neat... lol... Thanks!
