### ISSUE TITLE
Blog Demo Content is inappropriate

### ISSUE THREAD

**Issue by mattdenn** [Code52/metro.css#24]
I think someone has applied verbal graphitti to this.  It certainly isn't lipsum anymore

**Comment by shiftkey** [comment]
It was a variation of lorem ipsum called [SAMUEL L. IPSUM](http://slipsum.com/).

I've now changed it to use [bacon ipsum](http://baconipsum.com/) - if you'd like to see something different in the demos feel free to contribute some content.
