### ISSUE TITLE
_config.yml is empty

### ISSUE THREAD

**Issue by jbueza** [Code52/metro.css#26]
Oh hai,

I was just wondering why _config.yml is empty? I couldn't find any documentation on this on the wiki. :o)

Cheers,
Jaime

**Comment by shiftkey** [comment]
From memory, I was testing it in pretzel (another of the Code52 projects) and it wasn't recognising it as a valid Jekyll site.

Details on what can be in the `_config.yml` can be found [here](https://github.com/mojombo/jekyll/wiki/Configuration)

**Comment by jbueza** [comment]
Thanks for the info @shiftkey  :o)
